// SETTINGS
export const SAVE_API_KEY = "SAVE_API_KEY";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const CHECK_API_KEY_REQUEST = "CHECK_API_KEY_REQUEST";
export const CHECK_API_KEY_SUCCESS = "CHECK_API_KEY_SUCCESS";
export const CHECK_API_KEY_FAILURE = "CHECK_API_KEY_FAILURE";
// GET MOVIES

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";

export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CHANGE_YEAR = "CHANGE_YEAR";
export const CHANGE_TYPE = "CHANGE_TYPE";

//MOVIE DESCRIPTION
export const GET_DESCRIPTION_REQUEST = "GET_DESCRIPTION_REQUEST";
export const GET_DESCRIPTION_SUCCESS = "GET_DESCRIPTION_SUCCESS";
export const GET_DESCRIPTION_FAILURE = "GET_DESCRIPTION_FAILURE";
